//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
#pragma warning disable 1591

namespace RustyLogic.RedDotNet.Service.Rql {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RqlServiceSoap", Namespace="http://reddot.de/cms/webservices/navigation/1_1")]
    public partial class RqlService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExecuteStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExecuteInThreadPoolOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExecuteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RqlService() {
            this.Url = global::RustyLogic.RedDotNet.Properties.Settings.Default.RedDotNet_Service_Rql_RqlService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExecuteStringCompletedEventHandler ExecuteStringCompleted;
        
        /// <remarks/>
        public event ExecuteInThreadPoolCompletedEventHandler ExecuteInThreadPoolCompleted;
        
        /// <remarks/>
        public event ExecuteCompletedEventHandler ExecuteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://reddot.de/cms/webservices/navigation/1_1/ExecuteString", RequestNamespace="http://reddot.de/cms/webservices/navigation/1_1", ResponseNamespace="http://reddot.de/cms/webservices/navigation/1_1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExecuteString(string command) {
            object[] results = this.Invoke("ExecuteString", new object[] {
                        command});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteStringAsync(string command) {
            this.ExecuteStringAsync(command, null);
        }
        
        /// <remarks/>
        public void ExecuteStringAsync(string command, object userState) {
            if ((this.ExecuteStringOperationCompleted == null)) {
                this.ExecuteStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteStringOperationCompleted);
            }
            this.InvokeAsync("ExecuteString", new object[] {
                        command}, this.ExecuteStringOperationCompleted, userState);
        }
        
        private void OnExecuteStringOperationCompleted(object arg) {
            if ((this.ExecuteStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteStringCompleted(this, new ExecuteStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://reddot.de/cms/webservices/navigation/1_1/ExecuteInThreadPool", RequestNamespace="http://reddot.de/cms/webservices/navigation/1_1", ResponseNamespace="http://reddot.de/cms/webservices/navigation/1_1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExecuteInThreadPool(string command) {
            this.Invoke("ExecuteInThreadPool", new object[] {
                        command});
        }
        
        /// <remarks/>
        public void ExecuteInThreadPoolAsync(string command) {
            this.ExecuteInThreadPoolAsync(command, null);
        }
        
        /// <remarks/>
        public void ExecuteInThreadPoolAsync(string command, object userState) {
            if ((this.ExecuteInThreadPoolOperationCompleted == null)) {
                this.ExecuteInThreadPoolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteInThreadPoolOperationCompleted);
            }
            this.InvokeAsync("ExecuteInThreadPool", new object[] {
                        command}, this.ExecuteInThreadPoolOperationCompleted, userState);
        }
        
        private void OnExecuteInThreadPoolOperationCompleted(object arg) {
            if ((this.ExecuteInThreadPoolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteInThreadPoolCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://reddot.de/cms/webservices/navigation/1_1/Execute", RequestNamespace="http://reddot.de/cms/webservices/navigation/1_1", ResponseNamespace="http://reddot.de/cms/webservices/navigation/1_1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Execute(string command) {
            this.Invoke("Execute", new object[] {
                        command});
        }
        
        /// <remarks/>
        public void ExecuteAsync(string command) {
            this.ExecuteAsync(command, null);
        }
        
        /// <remarks/>
        public void ExecuteAsync(string command, object userState) {
            if ((this.ExecuteOperationCompleted == null)) {
                this.ExecuteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteOperationCompleted);
            }
            this.InvokeAsync("Execute", new object[] {
                        command}, this.ExecuteOperationCompleted, userState);
        }
        
        private void OnExecuteOperationCompleted(object arg) {
            if ((this.ExecuteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ExecuteStringCompletedEventHandler(object sender, ExecuteStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ExecuteInThreadPoolCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ExecuteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591